# Generated by Django 4.1.2 on 2022-10-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('time', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movies', to='app.category')),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
